apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DATABASE_URL
              value: "{{ .Values.backend.env.databaseUrl }}"
            - name: BETTER_AUTH_SECRET
              value: "{{ .Values.backend.env.betterAuthSecret }}"
            - name: GROQ_API_KEY
              value: "{{ .Values.backend.env.groqApiKey }}"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
